# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160814_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='Sr', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='salutation',
            field=models.CharField(default='luis@gmail.com', max_length=10),
            preserve_default=False,
        ),
    ]
